version: '3'


services:
  web:
    build: .
    image: dwh_his_sync_allemrs
    volumes:
      - .:/project    
    depends_on:
      - mysql
    ports:
      - "5001:5000"
    environment:
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python app.py 0.0.0.0:5000 
