version: '3'


services:
  dwh_his_sync_allemrs:
    build: .
#    image: dwh_his_sync_allemrs
    volumes:
      - .:/project
    ports:
      - "5010:5000"
    environment:
      MODULE_WEB_ADMIN: 'true'
    env_file: ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python app.py 0.0.0.0:5000 
