name: Deployment CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD_HOST }}
        username: ${{ secrets.CICD_USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/githubworkflows/
          sudo chown -R cicd:cicd SyncAllEMRs
          cd SyncAllEMRs && git pull https://github.com/palladiumkenya/SyncAllEMRs.git
          sudo cp /apps/dockerApps/SyncAllEMRs/Dockerfile .
          sudo cp /apps/dockerApps/SyncAllEMRs/docker-compose.yml .
          sudo cp /apps/dockerApps/SyncAllEMRs/.env .
          docker-compose stop dwh_his_sync_allemrs &&  docker-compose rm -f dwh_his_sync_allemrs
          docker-compose up -d
          echo "done"
          
